name: Job Alert Bot

on:
  schedule:
    # 1시간마다 한 번씩 실행 (UTC 기준)
    - cron: '0/5 * * * *'
  # 필요할 때 수동으로 바로 실행할 수 있는 버튼을 만듭니다.
  workflow_dispatch:

permissions:
  # 스크립트가 last_jobs.json 파일을 업데이트하고 저장소에 다시 쓸 수 있게 허용합니다.
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 파이썬 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. 라이브러리 설치
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4. 스크립트 실행
      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python job_bot.py

      - name: Run Uman Bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python uman_bot.py
        
      # 5. 변경된 last_jobs.json 파일을 다시 저장소에 업데이트 (중복 방지용)
      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_jobs.json last_posts.json
          git commit -m "Update last seen items" || echo "No changes to commit"
          git push
